spring.application.name=NotificationService

#DataBase Connection
spring.dataSource.url=jdbc:mysql://localhost:3306/notificationDb
spring.dataSource.username=root
spring.dataSource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Hibernate Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


